spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.102:3306/cell?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 123456
    jpa:
    show-sql: true
server:
    context-path: /sell

#logging:
#    pattern:
#        console: "%d - %msg%n"
#    path: /var/log/tomcat/
#    file: /var/log/tomcat/sell.log
#    level: debug